config/routes.rb
Fit::Application.routes.draw do

  root :to => "home#show"

  get "pagamento/index"

  get "pagamento/confirmar"

  get "reserve_aula/new"

  get "aulas/new"

  get "aulas/index"

  get "cidade/index"

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "sign_up" => "users#new", :as => "sign_up"
  get "perfil/:id" => "users#show", :as => "perfil"

  match 'promote' => 'users#promote', :as => "promote"
  match 'demote' => 'users#demote', :as => "demote"
  match 'ginasiosperto' => 'ginasios#pertocidade', :as => "ginasiosperto"
  match '/users/:id/mudarpassword' => 'users#edit_password', :as => "mudarpassword"
  match '/users/:user_id/planos/requisitarplano' => 'planos#requisitar_plano', :as => "requisitarplano"
  match 'apagarpedido' => 'pedido_planos#destroy', :as => "apagarpedido"
  match 'confirmarpagamento' => 'pagamentos#confirmar', :as => "confirmarpagamento"
  match 'cancelarpagamento' => 'pagamentos#cancelar', :as => "cancelarpagamento"
  match 'cancelarmarcacao' => 'reserva_aulas#destroy', :as => "cancelarmarcacao"
  match 'efetuarmarcacao' => 'reserva_aulas#create', :as => "efetuarmarcacao"
  match '/ginasios/:ginasio_id/estatisticasmodalidade' => 'estatisticas#modalidade', :as => "estatisticasmodalidade"
  match '/ginasios/:ginasio_id/estatisticasmodalidadesemana' => 'estatisticas#modalidade_semana', :as => "estatisticasmodalidadesemana"
  match '/ginasios/:ginasio_id/estatisticasmodalidadeprofessor' => 'estatisticas#modalidade_professor', :as => "estatisticasmodalidadeprofessor"
  match '/ginasios/:ginasio_id/estatisticasaulasprofessor' => 'estatisticas#aulas_professor', :as => "estatisticasaulasprofessor"
  match '/ginasios/:ginasio_id/totalginasio' => 'estatisticas#total_ginasio', :as => "totalginasio"

  resources :users do
    resources :planos
    resources :reserva_aulas
    resources :pagamentos
    resources :alimentar_planos
  end

  resources :tipo_aulas
  resources :exercicios
  resources :sessions
  resources :notificacaos
  resources :reserva_aulas
  resources :pedido_planos
  resources :modalidade_pagamentos
  resources :pagamentos


  resources :ginasios do
    resources :users
    resources :estudios
    resources :estatisticas
    resources :aulas do

      resources :reserva_aulas

    end
  end



  namespace :api do
    resources :users
    resources :planos
    resources :exercicios
    resources :sessions
    resources :notificacaos
    resources :ginasios
    resources :aulas
    resources :reserva_aulas
    resources :pedido_planos
    resources :feedbacks
    resources :pagamentos
    resources :alimentar_planos
    match 'desmarcar' => 'reserva_aulas#destroy', :as => "desmarcar"
    match 'users/edit' => 'users#edit', :as => "users/edit"
    match 'getinfo' => 'reserva_aulas#get_info', :as => "getinfo"
  end

  
  

end

app/models/notificacao.rb
class Notificacao < ActiveRecord::Base

  belongs_to :admin

  validates_presence_of :titulo, :message => "em branco. Introduza o titulo da notificacao."
  validates_presence_of :texto, :message => "em branco. Escreva a mensagem que pretende divulgar."
  validates_presence_of :admin_id, :message => "em branco."

end

app/controllers/api/notificacaos_controller.rb
class Api::NotificacaosController < ApiController
  def index
		  @user = User.find_by_token(params[:token])
		  @notificacoes = Notificacao.where(:ginasio_id => @user.ginasio_id)
		  
			Notificacao.where(:ginasio_id => nil).each do |n|

				@notificacoes << n

    	end

    	render :xml => @notificacoes
  end

  def show
		respond_with Notificacao.find(params[:id])
  end
end

app/controllers/notificacaos_controller.rb
class NotificacaosController < ApplicationController
	load_and_authorize_resource  

  # GET /notificacaos
  # GET /notificacaos.json
  def index
    @notificacaos = Notificacao.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @notificacaos }
    end
  end

  # GET /notificacaos/1
  # GET /notificacaos/1.json
  def show
    @notificacao = Notificacao.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @notificacao }
    end
  end

  # GET /notificacaos/new
  # GET /notificacaos/new.json
  def new
    @notificacao = Notificacao.new
	@notificacao.data = Date.today

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @notificacao }
    end
  end

  # GET /notificacaos/1/edit
  def edit
    @notificacao = Notificacao.find(params[:id])
  end

  # POST /notificacaos
  # POST /notificacaos.json
  def create
		
		if current_user.admin?
			params[:notificacao][:admin_id] = current_user.id
		end
		params[:notificacao][:data] = Date.today
		if params[:todos]
			params[:notificacao][:ginasio_id] = nil
    end
    @notificacao = Notificacao.new(params[:notificacao])

    

    respond_to do |format|
      if @notificacao.save
        format.html { redirect_to @notificacao, :flash => { :success => "Notificacao criada com sucesso." } }
        format.json { render :json => @notificacao, :status => :created, :location => @notificacao }
      else
        format.html { render :action => "new" }
        format.json { render :json => @notificacao.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /notificacaos/1
  # PUT /notificacaos/1.json
  def update
	
    if params[:todos]
	params[:notificacao][:ginasio_id] = nil
    end

    @notificacao = Notificacao.find(params[:id])

    respond_to do |format|
      if @notificacao.update_attributes(params[:notificacao])
        format.html { redirect_to @notificacao, :flash => { :success => "Notificacao alterada com sucesso." } }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @notificacao.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /notificacaos/1
  # DELETE /notificacaos/1.json
  def destroy
    @notificacao = Notificacao.find(params[:id])
    @notificacao.destroy

    respond_to do |format|
      format.html { redirect_to notificacaos_url }
      format.json { head :ok }
    end
  end
end

app/helpers/notificacaos_helper.rb
module NotificacaosHelper
end

app/views/notificacaos/_form.html.erb
<% content_for :head do %>
<script type="text/javascript">
$(document).ready(function() {
  $("#form_notificacao").validate( {
    rules: {
      "notificacao[titulo]": {
        required: true,
        minlength: 2
      },
      "notificacao[texto]": {
        required: true,
        minlength: 2
      }
    },
    messages: {
      "notificacao[titulo]": "O titulo não pode estar em branco",
      "notificacao[texto]": "O conteúdo da notificação está em branco"
    },

    // add/remove bootstrap error classes
    highlight: function (element, errorClass, validClass) {
      $(element).parents("div[class='clearfix']").addClass("error");
    },
    unhighlight: function (element, errorClass, validClass) {
      $(element).parents(".error").removeClass("error");
    },
    errorElement: 'p'
  });

});
</script>
<% end %>

<%= form_for(@notificacao, :html => {:id => "form_notificacao"}) do |f| %>
  <% if @notificacao.errors.any? %>
    <div class="alert-message block-message error">
      <p>
        <strong>Oh snap! O formulário tem alguns erros.</strong>
        Veja aquilo que tem de mudar:
      </p>
      <ul>
        <% @notificacao.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="clearfix">
    <%= f.label :data %>
    <div class="input">
      <%= f.text_field :data , :disabled => true, :class => "span3" %>
    </div>
  </div>	

  <div class="clearfix">
    <%= label_tag :cidade, 'Cidade' %>
    <div class="input">
      <%= collection_select("notificacao", "ginasio_id", Ginasio.all, :id, :nome, {}, { :id => "ginasios_select", :class => "span3" }) %>
    </div>
  </div>

  <div class="clearfix">
    <div class="input">
    <ul class="inputs-list">
      <li>
        <label>
          <%= check_box_tag :todos, 'Todos os ginásios' %>
          <span>Todos os ginásios</span>
        </label>
      </li>
    </ul>
    </div>
  </div>

  <div class="clearfix">
    <%= f.label :titulo %>
    <div class="input">
      <%= f.text_field :titulo, :class => "span9" %>
    </div>
  </div>

  <div class="clearfix">
    <%= f.label :texto %>
    <div class="input">
      <%= f.text_area :texto, { :rows => 13, :class => "span9 vertical-resize" } %>
    </div>
  </div>

  <div class="actions topSpacing0">
    <%= f.submit 'Guardar', :class => "btn success" %>
    <!-- closed outside on new.html and edit.html -->
<% end %>

app/views/notificacaos/edit.html.erb
<div class="span12">
  <h1>Editar Notificação</h1>

  <%= render 'form' %>
    <%= link_to 'Cancelar', @notificacao, :class => "btn danger" %>
    <%= link_to 'Ver Notificações', notificacaos_path, :class => "btn primary" %>
  </div>
</div>

app/views/notificacaos/index.html.erb
<div class="span14">
  <h1>Notificações gerais</h1>

  <table class="zebra-striped">
    <% if @notificacaos.empty? %>
      <tr>
        <td colspan="2"> &lt;Não existem notificações.&gt;</td>
      </tr>
    <% else %>
    <% @notificacaos.each do |notificacao| %>
      <% if notificacao.ginasio_id == nil %>
      <tr>
        <td class="span10"><%= link_to notificacao.titulo, notificacao %>
        <td>por <%= link_to User.find(notificacao.admin_id).nome, user_path(notificacao.admin_id) %> em <%= notificacao.data %></td>

        <% if can? :delete, Notificacao %>
        <td><%= link_to 'Apagar', notificacao, :confirm => 'Tem a certeza que deseja apagar esta notificação?', :method => :delete %></td>
        <% end %>
      </tr>
      <% end %>
    <% end %>
    <% end %>
  </table>

  <%if current_user.admin? || current_user.staff?%>
    <h1>Notificações de ginásios</h1>
  <%else%>
    <h1>Notificações do seu ginásio</h1>
  <%end%>

  <table>
    <% if @notificacaos.empty? %>
      <tr>
        <td>&lt;Não existem notificações.&gt; </td>
      </tr>
    <% else %>
    <% @notificacaos.each do |notificacao| %>
      <% if (((current_user.admin? || current_user.staff?) && notificacao.ginasio_id != nil) || (current_user.normal? && notificacao.ginasio_id == current_user.ginasio_id)) %>
      <tr>
        <td><%= link_to notificacao.titulo, notificacao %>
 	
        <td>por <%= link_to User.find(notificacao.admin_id).nome, user_path(notificacao.admin_id) %> em <%= notificacao.data %></td>
	<%if current_user.admin? || current_user.staff?%>
		<td> no <%= Ginasio.find(notificacao.ginasio_id).nome %></td>
	<%end%>
        <% if can? :delete, Notificacao %>
        <td><%= link_to 'Apagar', notificacao, :confirm => 'Tem a certeza que deseja apagar esta notificação?', :method => :delete %></td>
        <% end %>
	
      </tr>
      <% end %>
    <% end %>
    <% end %>
  </table>

  <div class="actions topSpacing0">
    <%= link_to 'Criar Notificação', new_notificacao_path, :class => "btn primary" unless !current_user.admin? %>
  </div>

</div>

app/views/notificacaos/index.mobile.erb
<div class="mobile-content">
<h3>Notificações gerais</h3>

<table class="zebra-striped">
	<% @notificacaos.each do |notificacao| %>
      <% if notificacao.ginasio_id == nil %>
      <tr>
        <td class="mobile">
		<%= link_to notificacao do %>
		<div class="mobile-cell">
			<%= notificacao.titulo %>
			<p class="mobile-description"> <%= User.find(notificacao.admin_id).nome %> em <%= notificacao.data %> </p>	
		</div>
		<% end %>
		</td>
      </tr>
      <% end %>
    <% end %>
</table>

<h3> Notificações do seu ginásio </h3>

<table class="zebra-striped">
    <% @notificacaos.each do |notificacao| %>
      <% if (current_user.normal? && notificacao.ginasio_id == current_user.ginasio_id) %>
      <tr>
        <td class="mobile">
		<%= link_to notificacao do %>
        <div class="mobile-cell">
			<%= notificacao.titulo %>
			<p class="mobile-description"> <%= User.find(notificacao.admin_id).nome %> em <%= notificacao.data %></p>
		</div>
		<% end %>
		</td>
      </tr>
      <% end %>
    <%end%>
</table>

<%= link_to 'Voltar', new_session_path, :class => "btn primary" %>

</div>

app/views/notificacaos/new.html.erb
<div class="span12">
  <h1>Criar Notificação</h1>

  <%= render 'form' %>
    <%= link_to 'Cancelar', notificacaos_path, :class => "btn danger" %>
  </div>
</div>

app/views/notificacaos/show.html.erb
<div class="span14">
  <h1>Notificação</h1>
  <h3><%= @notificacao.titulo %></h3>

  <div class="row">
    <div class="span12">
      <div class="well">
        <p>
          <% @notificacao.texto.split("\r\n").each do |line| %>
          <%= line %> <br/>
          <% end %>
        </p>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="span6">
      <!--<p><em>Criado por <%= User.find(@notificacao.admin_id).nome %> em <%= @notificacao.data %></em></p>-->
      <p>
        <em>Criado por </em>
        <strong><%= link_to User.find(@notificacao.admin_id).nome, user_path(@notificacao.admin_id) %></strong>
        <em>em <%= @notificacao.data %> </em>
      </p>
    </div>
  </div>

  <div class="actions topSpacing0">
    <%= link_to 'Editar Notificação', edit_notificacao_path(@notificacao), :class => "btn primary" %>
    <%= link_to 'Voltar', notificacaos_path, :class => "btn" %>
  </div>

</div>

app/views/notificacaos/show.mobile.erb
<div class="mobile-content">

<h3>Notificação</h3>
<h4><%= @notificacao.titulo %></h4>

<p>
    <% @notificacao.texto.split("\r\n").each do |line| %>
    <%= line %> <br/>
    <% end %>
</p>

<p class="mobile-description">
        <em>Criado por </em>
        <strong><%= User.find(@notificacao.admin_id).nome %></strong>
        <em>em <%= @notificacao.data %> </em>
</p>

</br>

<%= link_to 'Voltar', notificacaos_path, :class => "btn primary" %>

</div>