config/routes.rb
Fit::Application.routes.draw do

  root :to => "home#show"

  get "pagamento/index"

  get "pagamento/confirmar"

  get "reserve_aula/new"

  get "aulas/new"

  get "aulas/index"

  get "cidade/index"

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "sign_up" => "users#new", :as => "sign_up"
  get "perfil/:id" => "users#show", :as => "perfil"

  match 'promote' => 'users#promote', :as => "promote"
  match 'demote' => 'users#demote', :as => "demote"
  match 'ginasiosperto' => 'ginasios#pertocidade', :as => "ginasiosperto"
  match '/users/:id/mudarpassword' => 'users#edit_password', :as => "mudarpassword"
  match '/users/:user_id/planos/requisitarplano' => 'planos#requisitar_plano', :as => "requisitarplano"
  match 'apagarpedido' => 'pedido_planos#destroy', :as => "apagarpedido"
  match 'confirmarpagamento' => 'pagamentos#confirmar', :as => "confirmarpagamento"
  match 'cancelarpagamento' => 'pagamentos#cancelar', :as => "cancelarpagamento"
  match 'cancelarmarcacao' => 'reserva_aulas#destroy', :as => "cancelarmarcacao"
  match 'efetuarmarcacao' => 'reserva_aulas#create', :as => "efetuarmarcacao"
  match '/ginasios/:ginasio_id/estatisticasmodalidade' => 'estatisticas#modalidade', :as => "estatisticasmodalidade"
  match '/ginasios/:ginasio_id/estatisticasmodalidadesemana' => 'estatisticas#modalidade_semana', :as => "estatisticasmodalidadesemana"
  match '/ginasios/:ginasio_id/estatisticasmodalidadeprofessor' => 'estatisticas#modalidade_professor', :as => "estatisticasmodalidadeprofessor"
  match '/ginasios/:ginasio_id/estatisticasaulasprofessor' => 'estatisticas#aulas_professor', :as => "estatisticasaulasprofessor"
  match '/ginasios/:ginasio_id/totalginasio' => 'estatisticas#total_ginasio', :as => "totalginasio"

  resources :users do
    resources :planos
    resources :reserva_aulas
    resources :pagamentos
    resources :alimentar_planos
  end

  resources :tipo_aulas
  resources :exercicios
  resources :sessions
  resources :notificacaos
  resources :reserva_aulas
  resources :pedido_planos
  resources :modalidade_pagamentos
  resources :pagamentos


  resources :ginasios do
    resources :users
    resources :estudios
    resources :estatisticas
    resources :aulas do

      resources :reserva_aulas

    end
  end



  namespace :api do
    resources :users
    resources :planos
    resources :exercicios
    resources :sessions
    resources :notificacaos
    resources :ginasios
    resources :aulas
    resources :reserva_aulas
    resources :pedido_planos
    resources :feedbacks
    resources :pagamentos
    resources :alimentar_planos
    match 'desmarcar' => 'reserva_aulas#destroy', :as => "desmarcar"
    match 'users/edit' => 'users#edit', :as => "users/edit"
    match 'getinfo' => 'reserva_aulas#get_info', :as => "getinfo"
  end

  
  

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :admins
  has_many :staffs
  has_many :planos
  has_many :reserva_planos

  belongs_to :ginasio
  belongs_to :modalidade_pagamento
  has_one :pedido_plano

  attr_accessible :email, :password, :password_confirmation, :nome, :morada, :telefone, :datanascimento, :url_foto, :ginasio_id, :modalidade_pagamento_id

  attr_accessor :password
  before_save :encrypt_password
  before_create :set_token

  validates_presence_of :nome, :message => "esta em branco."

  validates_presence_of :datanascimento, :message => "em branco."
  validates_format_of :datanascimento, :message => "invalida. (yyyy/mm/dd)",
    :with => /^(19\d\d|2\d\d\d)([- \/.])(0[1-9]|1[012])\2(0[1-9]|[12][0-9]|3[01])$/,
    :unless => Proc.new { |user| user.datanascimento.blank? }

  validates_presence_of :email, :on => :create, :message => "em branco. Introduza o seu email (ex: exemplo@sapo.pt)"
  validates_uniqueness_of :email, :on => :create, :message => "ja existente na base de dados. Introduza outro email."
  validates_format_of :email, :on => :create,
    :unless => Proc.new { |user| user.email.blank? },
    :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/,
    :message => "invalido. Introduza o seu email (ex: exemplo@sapo.pt)"

  validates_presence_of :telefone, :message => "em branco."
  validates_format_of :telefone, :unless => Proc.new { |user| user.telefone.blank? },
    :with => /^((\+351|00351|351)(\s{1})?)?(2\d{1}|(9(3|6|2|1)))\d{7}$/, :message => "invalido."

  validates_presence_of :morada, :message => "em branco."
  validates_presence_of :ginasio_id

  validates_presence_of :password, :on => :create, :message => "em branco."
  validates_length_of :password, :on => :create, :in => 6..20,
    :unless => Proc.new { |user| user.password.blank? },
    :too_long => "demasiado grande. Tem de ter entre 6 a 20 caracteres",
    :too_short => "demasiado pequena. Tem de ter entre 6 a caracteres"
  validates_confirmation_of :password, :message => "diferente."

  validates_presence_of :modalidade_pagamento_id, :unless => Proc.new { |user| user.admin? || user.staff? }
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def generate_password

    generated = Digest::SHA1.hexdigest("--#{Time.now.to_s}--#{nome}--")[0,6]
    self.password = generated
    self.password_confirmation = generated
    return generated
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def set_token
    self.token = UUIDTools::UUID.timestamp_create.to_s
  end

  # Admins and staff
  def admin?
    if(Admin.find_by_user_id(id) != nil) 
      return true
    else
      return false
    end
  end
  
  def staff?
    if(Staff.find_by_user_id(id) != nil) 
      return true
    else
      return false
    end  
  end

  def normal?
    !admin? && !staff? && id != nil
  end

  # Promotions and Relegations
  def promote
    if normal?
      Staff.create(:user_id => id)
    elsif staff?
      Admin.create(:user_id => id)
      Staff.find_by_user_id(id).destroy
    end
     
  end

  def demote
    if admin?
      Staff.create(:user_id => id)
      Admin.find_by_user_id(id).destroy
    elsif staff?
      Staff.find_by_user_id(id).destroy
    end
  end

  # Profile photo
  require 'flickraw'
  def flickr_auth
    FlickRaw.api_key="755298909a3867da9092eb921e173531"
    FlickRaw.shared_secret="3586b0ced741121d"
    flickr.access_token = "72157628068928565-9a350e8521dbe649"
    flickr.access_secret = "85c3c8966a036c44"

    login = flickr.test.login
  end

  def upload_foto(file)
    login = flickr.test.login

    directory = "tmp"
    path = File.join(directory,file.original_filename)
    File.open(path, "wb") { |f| f.write(file.read) }
    
    return flickr.upload_photo path
  end
  
  def get_foto
    FlickRaw.api_key="755298909a3867da9092eb921e173531"
    FlickRaw.shared_secret="3586b0ced741121d"

    info = flickr.photos.getInfo(:photo_id => url_foto)
    return FlickRaw.url_m(info)
  end

  require 'builder'
  def to_xml(options ={})
    xml = ::Builder::XmlMarkup.new(:indent=>2)
    xml.instruct!

    xml.user do
      xml.nome nome
      xml.datanascimento datanascimento
      xml.telefone telefone
      xml.morada morada
      xml.email email
      xml.ginasio ginasio_id
      xml.token token

      if url_foto
        xml.foto get_foto
      else
        xml.foto "http://fitec.heroku.com/images/missing.png"
      end
    end
  end

end

app/controllers/api/users_controller.rb
class Api::UsersController < ApiController

  def index
    respond_with User.find_by_token(params[:token]) 
  end

  def edit
    @user = User.find_by_token(params[:token])
    

    if @user.update_attributes(:nome => params[:nome], :email => params[:email], :datanascimento => params[:datanascimento],
                                :morada => params[:morada], :telefone => params[:telefone])
      
      render :xml => message("success")
    else
      render :xml => message("fail")
    end
  end

  def message(msg)
    xml = Builder::XmlMarkup.new(:indent=>2)
    xml.instruct!

    xml.edit do
        xml.message msg
    end
  end

  skip_before_filter :verify_authenticity_token
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  def index
    if params[:ginasio_id]
      @users = User.where(:ginasio_id => params[:ginasio_id])
    else
      @users = User.find(:all, :order => 'id')
    end
  end

  def new
    @user = User.new
  end

  def create
    params[:user][:email] = params[:user][:email].downcase

    @user = User.new(params[:user])

    pw_gerada = @user.generate_password

    if @user.save
      if params[:filename] && params[:filename] != ""
        @user.flickr_auth
        url_foto = @user.upload_foto(params[:filename])
        @user.update_attributes(:url_foto => url_foto)
      end 
      redirect_to @user, :flash => { :success => "Utilizador registado com sucesso!" }
      FitMailer.welcome_email(@user, pw_gerada).deliver
    else
      render "new"
    end  
  end

  # GET /exercicios/1/edit
  def edit
    @user = User.find(params[:id])
  end

   # GET /exercicios/1/edit
  def edit_password
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if params[:filename] && params[:filename] != ""
      @user.flickr_auth
      params[:user][:url_foto] = @user.upload_foto(params[:filename])
    end

    respond_to do |format|

      if params[:password_antiga]

        if !User.authenticate(@user.email,params[:password_antiga])
          format.html { render :action => "edit_password", :flash => { :error => "Password antiga nao esta correta" } }
        elsif @user.update_attributes(params[:user])
          format.html { redirect_to(@user, :flash => { :success => "Password alterada!" }) }
        else
          format.html { render :action => "edit_password", :flash => { :error => "Erro ao mudar a password" } }
        end
      else
        if @user.update_attributes(params[:user])
          format.html { redirect_to(@user, :flash => { :success => "Dados actualizados com sucesso!" }) }
        else
          format.html { render :action => "edit" }
        end

      end      
    end
  end

  # GET /exercicios/1
  # GET /exercicios/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
      format.json  { render :json => @user }
    end
  end

  # DELETE /exercicios/1
  # DELETE /exercicios/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end

  def promote
    @user = User.find(params[:id])
    @user.promote

    if @user.staff?
      redirect_to @user, :flash => { :success => "Utilizador " + @user.nome + " promovido a Staff com sucesso." }
    elsif @user.admin?
      redirect_to @user, :flash => { :success => "Utilizador " + @user.nome + " promovido a Administrador com sucesso." }
    end
     
  end

  def demote
    @user = User.find(params[:id])
    @user.demote

    if @user.staff?
      redirect_to @user, :flash => { :success => "Utilizador " + @user.nome + " relegado a Staff com sucesso." }
    elsif @user.normal?
      redirect_to @user, :flash => { :success => "Utilizador " + @user.nome + " relegado a Utilizador com successo." }
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<% content_for :head do %>
<%= javascript_include_tag "validate-user-form.js" %>

<script type="text/javascript">
  $(document).ready(function() {

    jQuery.validator.addMethod("exactLength", function(value, element, param) {
      return this.optional(element) || value.length == param;
    }, jQuery.format("Please enter exactly {0} characters."));
  
    jQuery.validator.addMethod("passwordValidation", function(value, element, param) {
      if (this.optional(element))
        return true;

      var re = /^\w*(?=\w*\d)(?=\w*[a-z])(?=\w*[A-Z])\w*$/;
      return re.test(value) == param;
    }, "Your password must include uppercase, lowercase and digit characters");

    jQuery.validator.addMethod("ptTelephone", function(value, element, param) {
      if (this.optional(element))
        return true;

      var re = /^((\+351|00351|351)(\s{1})?)?(2\d{1}|(9(3|6|2|1)))\d{7}$/;
      return re.test(value) == param;
    }, "Not a portuguese telephone number");

    validateUserForm("#new_user");
  });
</script>
<% end %>

<%= form_for @user, :html => { :multipart => true } do |f| %>

  <% if @user.errors.any? %>
    <div class="alert-message block-message error">
      <p>
        <strong>Oh snap! O formulário tem alguns erros.</strong>
        Veja aquilo que tem de mudar:
      </p>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="clearfix">
    <%= f.label :nome %>
    <div class="input">
      <%= f.text_field :nome, :class => "span7" %>
    </div>
  </div>

  <div class="clearfix">
    <%= f.label :datanascimento, "Data de Nascimento" %>
    <div class="input">
      <%= f.text_field :datanascimento, :class => "span2" %>
    </div>
  </div>

  <div class="clearfix">
    <%= f.label :email %>
    <div class="input">
      <%= f.text_field :email, :class => "span4" %>
    </div>
  </div>

  <div class="clearfix">
    <%= f.label :telefone %>
    <div class="input">
      <%= f.text_field :telefone, :class => "span2" %>
    </div>
  </div>

  <div class="clearfix">
    <%= f.label :morada %>
    <div class="input">
      <!-- <%= f.text_field :morada, :class => "span7" %> -->
      <%= f.text_area :morada, { :rows => 5, :class => "span6 no-resize" } %>
    </div>
  </div>

  <div class="clearfix">
    <%= f.label(:ginasio_id, 'Ginasio') %>
    <div class="input">
      <%= collection_select("user", "ginasio_id", Ginasio.all, :id, :nome, {}, {  :class => "span6 no-resize" }) %>
    </div>
  </div>
    
  <div class="clearfix">
    <%= f.label :modalidade_pagamento_id, 'Frequencia' %>
    <div class="input">
      <%= collection_select("user", "modalidade_pagamento_id", ModalidadePagamento.all, :id, :nome, {}, {  :class => "span6 no-resize" }) %>
    </div>
  </div>

  <div class="field">
    <%= label_tag :filename %>
    <div class="input">
      <%= file_field_tag :filename %>
    </div>
  </div>

  <div class="actions topSpacing0">
    <%= f.submit "Guardar", :class => "btn success" %>
    <%= link_to 'Cancelar', users_path, :class => "btn danger", :confirm => "Rejeitar alterações?" %>
  </div>
<% end %>

app/views/users/_form_edit_password.html.erb
<% content_for :head do %>
<%= javascript_include_tag "validate-user-form.js" %>

<script type="text/javascript">
  $(document).ready(function() {

    jQuery.validator.addMethod("exactLength", function(value, element, param) {
      return this.optional(element) || value.length == param;
    }, jQuery.format("Please enter exactly {0} characters."));
  
    jQuery.validator.addMethod("passwordValidation", function(value, element, param) {
      if (this.optional(element))
        return true;

      var re = /^\w*(?=\w*\d)(?=\w*[a-z])(?=\w*[A-Z])\w*$/;
      return re.test(value) == param;
    }, "Your password must include uppercase, lowercase and digit characters");

    validateUserForm("#edit_user");
  });
</script>
<% end %>

<%= form_for @user, :html => { :id => "edit_user", :multipart => true } do |f| %>

  <!-- le error messages header TODO -->
  <% if @user.errors.any? %>
    <div class="alert-message error">
      <p>
        <strong>Oh snap! O formulário tem alguns erros.</strong>
        Veja aquilo que tem de mudar:
      </p>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!-- le form fields -->
   <div class="clearfix">
    <%= label :password_antiga, 'Password Antiga' %>
    <div class="input">
      <%= password_field_tag :password_antiga %>
    </div>
  </div>

  <div class="clearfix">
    <%= f.label :password %>
    <div class="input">
      <%= f.password_field :password %>
    </div>
  </div>

  <div class="clearfix">
    <%= f.label :password_confirmation, "Confirmar Password" %>
    <div class="input">
      <%= f.password_field :password_confirmation %>
    </div>
  </div>

  <div class="actions topSpacing0">
    <%= f.submit 'Guardar alterações', :class => "btn success" %>
    <%= link_to 'Cancelar', users_path, :class => "btn danger" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="span16">
  <h1>Editar Utilizador</h1>

  <%= render 'form' %>

  <!-- <%= link_to 'Listar Utilizadores', users_path %> -->
</div>

app/views/users/edit_password.html.erb
<div class="span16">
  <h1>Editar Utilizador</h1>

  <%= render 'form_edit_password' %>

  <!-- <%= link_to 'Listar Utilizadores', users_path %> -->
</div>

app/views/users/index.html.erb
<div class="span16">
  <% if current_user && @users.count > 0 %>
  <h1>Utilizadores</h1>

  <table class="zebra-striped">
    <tr>
      <th>Nr.</th>
      <th>Nome</th>
      <th>Tipo</th>
    </tr>

    <% @users.each do |user| %>
    <tr>
      <td><%= user.id %></td>
      <td><%= user.nome %></td>

      <% if user.admin? %>
      <td> Administrador </td>
      <% elsif user.staff? %>
      <td> Staff </td>
      <% else %>
      <td> Normal </td>
      <% end %>

      <td><%= link_to 'Ver', user %></td>

      <td>
        <% if (user.normal? || user.staff?) && current_user.admin? %>
        <%= link_to 'Apagar', user, :confirm => 'Tem a certeza que deseja apagar este utilizador?', :method => :delete %>
        <% end %>
      </td>
    </tr>
    <% end %>

  </table>
  <% end %>

  <% if can? :create, User %>
  <div class="actions topSpacing0">
    <%= link_to 'Registar Novo Utilizador', new_user_path, :class => "btn primary" %>
  </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="span16">
  <h1>Novo Utilizador</h1>

  <%= render 'form' %>
  <!-- <%= link_to 'Listar Utilizadores', users_path %> -->
</div>

app/views/users/show.html.erb
<div class="span16">
  <h1>Perfil</h1>

  <!-- profile content -->
  <div class="row spaced-lines">
    <div class="span9">

      <div class="row">
        <div class="span3 right-align"><strong>Nome:</strong></div>
        <div class="span6"><%= @user.nome %></div>
      </div>

      <div class="row">
        <div class="span3 right-align"><strong>Ginásio:</strong></div>
        <div class="span6"><%= @user.ginasio.nome unless @user.ginasio_id == nil%></div>
      </div>

      <% if @user.normal? %>
        <div class="row">
          <div class="span3 right-align"><strong>Frequencia:</strong></div>
          <div class="span6"><%= @user.modalidade_pagamento.nome unless @user.modalidade_pagamento_id == nil%></div>
        </div>
      <% end %>

      <div class="row">
        <div class="span3 right-align"><strong>Email:</strong></div>
        <div class="span6"><%= @user.email %></div>
      </div>

      <div class="row">
        <div class="span3 right-align"><strong>Data de Nascimento:</strong></div>
        <div class="span6"><%= @user.datanascimento %></div>
      </div>

      <div class="row">
        <div class="span3 right-align"><strong>Telefone:</strong></div>
        <div class="span6"><%= @user.telefone %></div>
      </div>

      <div class="row">
        <div class="span3 right-align"><strong>Morada:</strong></div>
        <div class="span6">
          <address>
            <% @user.morada.split("\r\n").each do |line| %>
            <%= line %><br/>
            <% end %>
          </address>
        </div>
      </div>
    </div>

    <div class="span3">
      <% if @user.url_foto %>
        <%= image_tag @user.get_foto, :id => "profile-photo" %>

      <% else %>
        <%= image_tag "missing.png", :id => "profile-photo" %>
      <% end %>
    </div>
  </div>

  <!-- le action buttons -->
  <div class="actions topSpacing0">
    
    <div class ="row">
        <%= link_to "Ver Planos", user_planos_path(@user), :class => "btn" if @user.normal? %>   
        <%= link_to "Ver pagamentos", user_pagamentos_path(@user, :ano => Time.now.year), :class => "btn" if @user.normal?%>
        <%= link_to "Ver Planos Alimentares", user_alimentar_planos_path(@user), :class => "btn" if @user.normal?%> 
    </div>
    </br>
    <div class ="row">
        <%= link_to "Editar Perfil", edit_user_path(@user), :class => "btn primary" %>
        <%= link_to "Alterar password", mudarpassword_path(@user), :class => "btn primary" if can? :edit_password, User %>
        
        <%= link_to "Promover", { :controller => "users" , :action => "promote", :id => @user}, :class => "btn success" if can?(:promote, User) && !@user.admin? %>
        <%= link_to "Despromover", { :controller => "users" , :action => "demote", :id => @user}, :class => "btn danger" if can?(:demote, User) && !@user.normal? %>
        <%= link_to "Listar utilizadores", users_path, :class => "btn danger"%>
    </div>    

  </div>
</div>

app/views/users/show.mobile.erb
<div class="mobile-content">

	<h3>Perfil</h3>

	<% if @user.url_foto %>
		<%= image_tag @user.get_foto, :id => "profile-photo", :class => "mobile-image" %>
	<% else %>
		<%= image_tag "missing.png", :id => "profile-photo", :class => "mobile-image" %>
	<% end %>

	<ul class = "mobile-list">
	<li><p> <b>Nome:</b> <%= @user.nome %></p></li>
	<li><p> <b>Ginásio:</b> <%= Ginasio.find(@user.ginasio_id).nome %></p></li>
	<li><p> <b>Email:</b> <%= @user.email %></p></li>
	<li><p> <b>Data de Nascimento:</b> <%= @user.datanascimento %></p></li>
	<li><p> <b>Telefone:</b> <%= @user.telefone %></p></li>
	<li><p> <b>Morada:</b> <%= @user.morada %></p></li>
	</ul>
	
	<ul class = "mobile-btn-list">
		<li><p><%= link_to 'Planos de Treino', user_planos_path(@user), :class=> "btn success" %></p> </li>
		<li><p><%= link_to 'Planos Alimentares', user_alimentar_planos_path(@user), :class => "btn success"%></p></li>
		<li><p><%= link_to 'Pagamentos', user_pagamentos_path(@user, :ano => Time.now.year), :class => "btn danger"%></p> </li>
	</ul>
	
	
	<%= link_to 'Voltar', new_session_path, :class => "btn primary" %> 
	
</div>