config/routes.rb
Fit::Application.routes.draw do

  root :to => "home#show"

  get "pagamento/index"

  get "pagamento/confirmar"

  get "reserve_aula/new"

  get "aulas/new"

  get "aulas/index"

  get "cidade/index"

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "sign_up" => "users#new", :as => "sign_up"
  get "perfil/:id" => "users#show", :as => "perfil"

  match 'promote' => 'users#promote', :as => "promote"
  match 'demote' => 'users#demote', :as => "demote"
  match 'ginasiosperto' => 'ginasios#pertocidade', :as => "ginasiosperto"
  match '/users/:id/mudarpassword' => 'users#edit_password', :as => "mudarpassword"
  match '/users/:user_id/planos/requisitarplano' => 'planos#requisitar_plano', :as => "requisitarplano"
  match 'apagarpedido' => 'pedido_planos#destroy', :as => "apagarpedido"
  match 'confirmarpagamento' => 'pagamentos#confirmar', :as => "confirmarpagamento"
  match 'cancelarpagamento' => 'pagamentos#cancelar', :as => "cancelarpagamento"
  match 'cancelarmarcacao' => 'reserva_aulas#destroy', :as => "cancelarmarcacao"
  match 'efetuarmarcacao' => 'reserva_aulas#create', :as => "efetuarmarcacao"
  match '/ginasios/:ginasio_id/estatisticasmodalidade' => 'estatisticas#modalidade', :as => "estatisticasmodalidade"
  match '/ginasios/:ginasio_id/estatisticasmodalidadesemana' => 'estatisticas#modalidade_semana', :as => "estatisticasmodalidadesemana"
  match '/ginasios/:ginasio_id/estatisticasmodalidadeprofessor' => 'estatisticas#modalidade_professor', :as => "estatisticasmodalidadeprofessor"
  match '/ginasios/:ginasio_id/estatisticasaulasprofessor' => 'estatisticas#aulas_professor', :as => "estatisticasaulasprofessor"
  match '/ginasios/:ginasio_id/totalginasio' => 'estatisticas#total_ginasio', :as => "totalginasio"

  resources :users do
    resources :planos
    resources :reserva_aulas
    resources :pagamentos
    resources :alimentar_planos
  end

  resources :tipo_aulas
  resources :exercicios
  resources :sessions
  resources :notificacaos
  resources :reserva_aulas
  resources :pedido_planos
  resources :modalidade_pagamentos
  resources :pagamentos


  resources :ginasios do
    resources :users
    resources :estudios
    resources :estatisticas
    resources :aulas do

      resources :reserva_aulas

    end
  end



  namespace :api do
    resources :users
    resources :planos
    resources :exercicios
    resources :sessions
    resources :notificacaos
    resources :ginasios
    resources :aulas
    resources :reserva_aulas
    resources :pedido_planos
    resources :feedbacks
    resources :pagamentos
    resources :alimentar_planos
    match 'desmarcar' => 'reserva_aulas#destroy', :as => "desmarcar"
    match 'users/edit' => 'users#edit', :as => "users/edit"
    match 'getinfo' => 'reserva_aulas#get_info', :as => "getinfo"
  end

  
  

end

app/models/tipo_aula.rb
class TipoAula < ActiveRecord::Base
	validates_presence_of :tipo, :message => "em branco."
	validates_presence_of :descricao, :message =>"em branco."


	def self.getVideoId(url)

		if url.blank?
			""
		elsif url[/youtu\.be\/([^\?]*)/]
			id = $1
		else
			url[/^.*((v\/)|(embed\/)|(watch\?))\??v?=?([^\&\?]*).*/]
			id = $5
		end

	end

end

app/controllers/tipo_aulas_controller.rb
class TipoAulasController < ApplicationController
  load_and_authorize_resource

  # GET /tipo_aulas
  # GET /tipo_aulas.json
  def index
    @tipo_aulas = TipoAula.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @tipo_aulas }
    end
  end

  # GET /tipo_aulas/1
  # GET /tipo_aulas/1.json
  def show
    @tipo_aula = TipoAula.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @tipo_aula }
    end
  end

  # GET /tipo_aulas/new
  # GET /tipo_aulas/new.json
  def new
    @tipo_aula = TipoAula.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @tipo_aula }
    end
  end

  # GET /tipo_aulas/1/edit
  def edit
    @tipo_aula = TipoAula.find(params[:id])
  end

  # POST /tipo_aulas
  # POST /tipo_aulas.json
  def create
    params[:tipo_aula][:video_id] = TipoAula.getVideoId(params[:tipo_aula][:video_id])
    @tipo_aula = TipoAula.new(params[:tipo_aula])

    respond_to do |format|
      if @tipo_aula.save
        format.html { redirect_to @tipo_aula, :flash => { :success => 'Tipo de aula (modalidade) criado com sucesso.' } }
        format.json { render :json => @tipo_aula, :status => :created, :location => @tipo_aula }
      else
        format.html { render :action => "new" }
        format.json { render :json => @tipo_aula.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tipo_aulas/1
  # PUT /tipo_aulas/1.json
  def update
    params[:tipo_aula][:video_id] = TipoAula.getVideoId(params[:tipo_aula][:video_id])
    @tipo_aula = TipoAula.find(params[:id])

    respond_to do |format|
      if @tipo_aula.update_attributes(params[:tipo_aula])
        format.html { redirect_to @tipo_aula, :flash => { :success => 'Tipo de aula (modalidade) alterado com sucesso.' } }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @tipo_aula.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tipo_aulas/1
  # DELETE /tipo_aulas/1.json
  def destroy
    @tipo_aula = TipoAula.find(params[:id])
    @tipo_aula.destroy

    respond_to do |format|
      format.html { redirect_to tipo_aulas_url, :flash => { :notice => 'Tipo Aula apagado.' } }
      format.json { head :ok }
    end
  end
end

app/helpers/tipo_aulas_helper.rb
module TipoAulasHelper

	

end

app/views/tipo_aulas/_form.html.erb
<% content_for :head do %>
<script type="text/javascript">
  $(document).ready(function() {
   
    $("#form_modalidade").validate( {
      rules: {
        "tipo_aula[tipo]": "required",
        "tipo_aula[descricao]": {
          required: true,
          minlength: 2,
        }
      },
      messages: {
        "tipo_aula[tipo]": "Introduza um nome válido (ciclismo, pesos, etc.)",
        "tipo_aula[descricao]": "Introduza uma descrição válida."
      },

      // add/remove bootstrap error classes
      highlight: function (element, errorClass, validClass) {
        $(element).parents("div[class='clearfix']").addClass("error");
      },
      unhighlight: function (element, errorClass, validClass) {
        $(element).parents(".error").removeClass("error");
      },
      errorElement: 'p'
    });
  });
</script>
<% end %>

<%= form_for(@tipo_aula, :html => { :id => "form_modalidade" }) do |f| %>
  <% if @tipo_aula.errors.any? %>
    <div class="alert-message block-message error">
      <p>
        <strong>Oh snap! O formulário tem alguns erros.</strong>
        Veja aquilo que tem de mudar:
      </p>
      <ul>
      <% @tipo_aula.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="clearfix">
    <%= f.label :tipo %>
    <div class="input">
      <%= f.text_field :tipo, :class => "span6" %>
    </div>
  </div>

  <div class="clearfix">
    <%= f.label :video_id, 'Video:' %>
    <div class="input">
      <%= f.text_field :video_id, :class => "span6" %>
    </div>
  </div>

  <div class="clearfix">
    <%= f.label :descricao, "Descrição" %>
    <div class="input">
      <%= f.text_area :descricao, { :rows => 8, :class => "span11 no-resize" } %>
    </div>
  </div>

  <div class="actions topSpacing1">
    <%= f.submit "Guardar", :class => "btn success" %>
    <%= link_to "Ver Modalidades", @tipo_aula, :class => "btn primary" %>
    <%= link_to "Cancelar", tipo_aulas_path, :class => "btn danger" %>
<% end %>

app/views/tipo_aulas/edit.html.erb
<div class="span14">
  <h1>Editar Modalidade</h1>

    <%= render 'form' %>
  </div>
</div>

app/views/tipo_aulas/index.html.erb
<div class="span16">
  <h1>Modalidades</h1>

  <table class="zebra-striped">
    <tr>
      <th>Nome</th>
    </tr>

  <% @tipo_aulas.each do |tipo_aula| %>
    <tr>
      <td><%= link_to tipo_aula.tipo, tipo_aula %></td>
    </tr>
  <% end %>
  </table>

  <% if can? :write, User %>
  <div class="actions topSpacing2">
    <%= link_to 'Nova modalidade', new_tipo_aula_path, :class => "btn primary" %>
  </div>
  <% end %>
</div>

app/views/tipo_aulas/index.mobile.erb
  <div class="mobile-content">
  
  <h3>Modalidades</h3>

  <table class="zebra-striped">
  <% @tipo_aulas.each do |tipo_aula| %>
    <tr>
      <td class="mobile"><%= link_to tipo_aula do %><div class="mobile-cell"><%= tipo_aula.tipo %></div><% end %></td>
    </tr>
  <% end %>
  </table>
  
  <%= link_to 'Voltar', new_session_path, :class => "btn primary" %>

</div>

app/views/tipo_aulas/new.html.erb
<div class="span14">
  <h1>Nova Modalidade</h1>

    <%= render 'form' %>
  </div>

  <!-- <%= link_to 'Back', tipo_aulas_path %> -->
</div>

app/views/tipo_aulas/show.html.erb
<div class="span14">

  <h1>Modalidade</h1>
  <h3> <%= @tipo_aula.tipo %> </h3>

  <br/>

  <div class = "span14 offset1">
    <p> <strong>Descrição:</strong> </p>
    <p> <%= @tipo_aula.descricao %> </p>
    
    <% if !@tipo_aula.video_id.blank? %>
      <iframe class ="centered-image" width="425" height="349" src="http://www.youtube.com/embed/<%=@tipo_aula.video_id%>" frameborder="0" allowfullscreen>
      </iframe>
    <% end %>
  </div>


  <div class="actions topSpacing1">
    <%= link_to 'Editar', edit_tipo_aula_path(@tipo_aula), :class => "btn success" %>
    <%= link_to 'Apagar', @tipo_aula, :confirm => 'Tem a certeza?', :method => :delete, :class => "btn danger" %>
    <%= link_to 'Voltar a modalidades', tipo_aulas_path, :class => "btn primary" %>
  </div>


</div>

app/views/tipo_aulas/show.mobile.erb
  <div class="mobile-content">

  <h3> <%= @tipo_aula.tipo %> </h3> </br>

  <p> <strong>Descrição:</strong> </p>
  <p> <%= @tipo_aula.descricao %> </p>

  	<% if !@tipo_aula.video_id.blank? %>
		<iframe width="200" height="200" src="http://www.youtube.com/embed/<%=@tipo_aula.video_id%>" frameborder="0" allowfullscreen>
		</iframe>
	<% end %>

  </br>
  <%= link_to 'Voltar', :back, :class => "btn primary" %>

  </div>