config/routes.rb
Fit::Application.routes.draw do

  root :to => "home#show"

  get "pagamento/index"

  get "pagamento/confirmar"

  get "reserve_aula/new"

  get "aulas/new"

  get "aulas/index"

  get "cidade/index"

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "sign_up" => "users#new", :as => "sign_up"
  get "perfil/:id" => "users#show", :as => "perfil"

  match 'promote' => 'users#promote', :as => "promote"
  match 'demote' => 'users#demote', :as => "demote"
  match 'ginasiosperto' => 'ginasios#pertocidade', :as => "ginasiosperto"
  match '/users/:id/mudarpassword' => 'users#edit_password', :as => "mudarpassword"
  match '/users/:user_id/planos/requisitarplano' => 'planos#requisitar_plano', :as => "requisitarplano"
  match 'apagarpedido' => 'pedido_planos#destroy', :as => "apagarpedido"
  match 'confirmarpagamento' => 'pagamentos#confirmar', :as => "confirmarpagamento"
  match 'cancelarpagamento' => 'pagamentos#cancelar', :as => "cancelarpagamento"
  match 'cancelarmarcacao' => 'reserva_aulas#destroy', :as => "cancelarmarcacao"
  match 'efetuarmarcacao' => 'reserva_aulas#create', :as => "efetuarmarcacao"
  match '/ginasios/:ginasio_id/estatisticasmodalidade' => 'estatisticas#modalidade', :as => "estatisticasmodalidade"
  match '/ginasios/:ginasio_id/estatisticasmodalidadesemana' => 'estatisticas#modalidade_semana', :as => "estatisticasmodalidadesemana"
  match '/ginasios/:ginasio_id/estatisticasmodalidadeprofessor' => 'estatisticas#modalidade_professor', :as => "estatisticasmodalidadeprofessor"
  match '/ginasios/:ginasio_id/estatisticasaulasprofessor' => 'estatisticas#aulas_professor', :as => "estatisticasaulasprofessor"
  match '/ginasios/:ginasio_id/totalginasio' => 'estatisticas#total_ginasio', :as => "totalginasio"

  resources :users do
    resources :planos
    resources :reserva_aulas
    resources :pagamentos
    resources :alimentar_planos
  end

  resources :tipo_aulas
  resources :exercicios
  resources :sessions
  resources :notificacaos
  resources :reserva_aulas
  resources :pedido_planos
  resources :modalidade_pagamentos
  resources :pagamentos


  resources :ginasios do
    resources :users
    resources :estudios
    resources :estatisticas
    resources :aulas do

      resources :reserva_aulas

    end
  end



  namespace :api do
    resources :users
    resources :planos
    resources :exercicios
    resources :sessions
    resources :notificacaos
    resources :ginasios
    resources :aulas
    resources :reserva_aulas
    resources :pedido_planos
    resources :feedbacks
    resources :pagamentos
    resources :alimentar_planos
    match 'desmarcar' => 'reserva_aulas#destroy', :as => "desmarcar"
    match 'users/edit' => 'users#edit', :as => "users/edit"
    match 'getinfo' => 'reserva_aulas#get_info', :as => "getinfo"
  end

  
  

end

app/models/ginasio.rb
class Ginasio < ActiveRecord::Base

  has_many :users
  has_many :pedido_planos
  has_many :estudios
  has_many :aulas

  attr_accessible :nome, :morada, :telefone

  geocoded_by :morada
  after_validation :geocode


  validates_presence_of :nome, :message => "do ginasio esta em branco."

  validates_presence_of :telefone, :message => "em branco. Introduza o telefone do ginasio."
  validates_format_of :telefone, :unless => Proc.new { |ginasio| ginasio.telefone.blank? },
    :with => /^((\+351|00351|351)(\s{1})?)?(2\d{1}|(9(3|6|2|1)))\d{7}$/,
    :message => "invalido. Introduza um numero de telefone valido."

  validates_presence_of :morada, :message => "em branco. Introduza a morada."
end

app/controllers/api/ginasios_controller.rb
class Api::GinasiosController < ApiController
  def index
    respond_with Ginasio.all
  end

  def show
    respond_with Ginasios.find(params[:id])  
  end
end

app/controllers/ginasios_controller.rb
class GinasiosController < ApplicationController
  load_and_authorize_resource 

  # GET /ginasios
  # GET /ginasios.json
  def index
    @ginasios = Ginasio.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @ginasios }
    end
  end

  def pertocidade
    results = Geocoder.search(params[:cidade])
    @ginasios = Ginasio.near([results[0].latitude,results[0].longitude],params[:km].to_f*0.62)
    respond_to do |format|
      format.xml { render :xml => @ginasios }
    end
  end

  # GET /ginasios/1
  # GET /ginasios/1.json
  def show
    @ginasio = Ginasio.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @ginasio }
    end
  end

  # GET /ginasios/new
  # GET /ginasios/new.json
  def new
    @ginasio = Ginasio.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @ginasio }
    end
  end

  # GET /ginasios/1/edit
  def edit
    @ginasio = Ginasio.find(params[:id])
  end

  # POST /ginasios
  # POST /ginasios.json
  def create
    @ginasio = Ginasio.new(params[:ginasio])

    respond_to do |format|
      if @ginasio.save
        format.html { redirect_to @ginasio, :flash => { :success => 'Ginasio criado com sucesso!' } }
        format.json { render :json => @ginasio, :status => :created, :location => @ginasio }
      else
        format.html { render :action => "new" }
        format.json { render :json => @ginasio.errors, :status => :unprocessable_entity }
      end
    end
  end	

  # PUT /ginasios/1
  # PUT /ginasios/1.json
  def update
    @ginasio = Ginasio.find(params[:id])

    respond_to do |format|
      if @ginasio.update_attributes(params[:ginasio])
        format.html { redirect_to @ginasio, :flash => { :success => 'Dados do ginasio alterados com successo!' } }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @ginasio.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /ginasios/1
  # DELETE /ginasios/1.json
  def destroy
    @ginasio = Ginasio.find(params[:id])
    @ginasio.destroy

    respond_to do |format|
      format.html { redirect_to ginasios_url, :flash => { :notice => 'Ginasio apagado.' } }
      format.json { head :ok }
    end
  end
end

app/helpers/ginasios_helper.rb
module GinasiosHelper
end

app/views/ginasios/_form.html.erb
<% content_for :head do %>

<script type="text/javascript">
  $(document).ready(function() {
   
    jQuery.validator.addMethod("exactLength", function(value, element, param) {
      return this.optional(element) || value.length == param;
    }, jQuery.format("Please enter exactly {0} characters."));

    $("#form_ginasio").validate( {
      rules: {
        "ginasio[nome]": {
          required: true,
          minlength: 2
        },
        "ginasio[telefone]": {
          required: true,
          digits: true,
          exactLength: 9
        },
        "ginasio[morada]": "required",
      },
      messages: {
        "ginasio[nome]": "O nome não pode estar em branco",
        "ginasio[telefone]": "Introduza o contacto do ginásio",
        "ginasio[morada]": "Introduza uma morada válida",
      },

      // add/remove bootstrap error classes
      highlight: function (element, errorClass, validClass) {
        $(element).parents("div[class='clearfix']").addClass("error");
      },
      unhighlight: function (element, errorClass, validClass) {
        $(element).parents(".error").removeClass("error");
      },
      errorElement: 'p'
    });
  });
</script>
<% end %>

<%= form_for(@ginasio, :html => { :id => "form_ginasio" }) do |f| %>
  <% if @ginasio.errors.any? %>
    <div class="alert-message block-message error">
      <p><strong>Oh snap!</strong> Alguns campos do formulário estão incorrectos.</p>

      <ul>
      <% @ginasio.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="clearfix">
    <%= f.label :nome %>
    <div class="input">
      <%= f.text_field :nome, :class => "span4" %>
    </div>
  </div>

  <div class="clearfix">
    <%= f.label :telefone %>
    <div class="input">
      <%= f.text_field :telefone, :class => "span4" %>
    </div>
  </div>
	
  <div class="clearfix">
    <%= f.label :morada %>
    <div class="input">
      <%= f.text_area :morada, { :rows => 5, :class => "span6 no-resize" } %>
    </div>
  </div>

  <div class="actions topSpacing1">
    <%= f.submit "Guardar", :class => "btn success" %>
<% end %>

app/views/ginasios/edit.html.erb
<div class="span14">
  <h1>Editar Ginásio</h1>

  <%= render 'form' %>

    <%= link_to 'Ver Ginásio', @ginasio, :class => "btn primary" %>
    <%= link_to 'Cancelar', ginasios_path, :class => "btn danger" %>
  </div>
</div>

app/views/ginasios/index.html.erb
<div class="span14">
  <h1>Lista de Ginásios</h1>

  <div class="row spaced-lines">
    <div class="span9">
      <div class="row">
        <div class="span3 right-align">
          <strong>Cidade</strong>
        </div>
        <div class="span6">
          <div class="clearfix">
            <div class="input">
              <%= text_field_tag :cidade, 'Porto', { :rows => 5, :class => "span6 no-resize", :id => "_cidade" } %>
            </div>
          </div>

        </div>
      </div>

      <div class="row">
        <div class="span3 right-align">
          <strong>Distancia</strong>
        </div>
        <div class="span6">
          <%= text_field_tag :distancia, '50', :class => "span1 no-resize" %> km
       </div>
      </div>
    </div>
  </div>

  <table id="ginasios">
    <tr>
      <th>Nome</th>
    </tr>
   
  </table>

  <div class="actions topSpacing2">
    <%= link_to 'Criar novo Ginásio', new_ginasio_path, :class => "btn primary" %>
  </div>

</div>

app/views/ginasios/index.mobile.erb
<div class="mobile-content">
<h3>Ginásios</h3>

<table class="zebra-striped">
	<% @ginasios.each do |ginasio| %>
      <tr>
        <td class="mobile">
		<%= link_to ginasio do %>
		<div class="mobile-cell">
			<%= ginasio.nome %>
		</div>
		<% end %>
		</td>
      </tr>
      <% end %>
</table>

<%= link_to 'Voltar', new_session_path, :class => "btn primary" %>

</div>

app/views/ginasios/new.html.erb
<div class="span14">
  <h1>Criar novo Ginásio</h1>

  <%= render 'form' %>

    <%= link_to 'Cancelar', ginasios_path, :class => "btn danger" %>
  </div>
</div>

app/views/ginasios/show.html.erb
<div class="span14">
  <h1><%=@ginasio.nome%></h1>

  <div class="row">
    <div class="span6">
      <p>
        <strong> Morada:</strong>
        <%= @ginasio.morada %>
      </p>
      <p>
        <strong> Telefone:</strong>
        <%= @ginasio.telefone %>
      </p>

      <p>
        <%= image_tag "http://maps.googleapis.com/maps/api/staticmap?center=#{@ginasio.latitude},#{@ginasio.longitude}&zoom=15&size=400x300\
&markers=color:blue%7C#{@ginasio.latitude},#{@ginasio.longitude}&sensor=false" %>
      </p>
    </div>
  </div>

  <div class="actions topSpacing2">
    <div class = "row">
        <%= link_to 'Editar Dados', edit_ginasio_path(@ginasio), :class => "btn success" if can? :update, Ginasio %>
        <%= link_to 'Ver Estatisticas', ginasio_estatisticas_path(@ginasio), :class => "btn success" if current_user.admin?%>
        <%= link_to 'Ver Utilizadores do Ginásio', ginasio_users_path(@ginasio), :class => "btn primary" if can? :read, User %>
    </div>
    </br>
    <div class = "row">
        <%= link_to 'Ver Aulas', ginasio_aulas_path(@ginasio), :class => "btn primary" %>
        <%= link_to 'Ver Estúdios', ginasio_estudios_path(@ginasio), :class => "btn primary" %>
        <%= link_to 'Ver Ginásios', ginasios_path, :class => "btn danger" %>
    </div>
  </div>
</div>

app/views/ginasios/show.mobile.erb
<div class="mobile-content">

	<h3>Ginásio</h3>
	<h4><%=@ginasio.nome%></h4>


      <p> <strong> Morada:</strong> <%= @ginasio.morada %> </p>
      <p> <strong> Telefone:</strong> <%= @ginasio.telefone %> </p>

      <p>
        <!-- {@ginasio.latitude},#{@ginasio.longitude} -->
        <%= image_tag "http://maps.googleapis.com/maps/api/staticmap?center=#{@ginasio.latitude},#{@ginasio.longitude}&zoom=15&size=400x300\&markers=color:blue%7C#{@ginasio.latitude},#{@ginasio.longitude}&sensor=false", :class => "mobile-map" %>
      </p>

	<%= link_to "Voltar", ginasios_path, :class => "btn primary" %>
    <%= link_to "Aulas" , ginasio_aulas_path(@ginasio), :class => "btn primary" %>
</div>